---

aws_access_key: ""
aws_secret_key: ""
aws_profile: NETWORK
region: "us-east-1"

# VPC
vpc_cidr: 10.10.0.0/24
vpc_name: "Network VPC"

# Subnet
subnet_name: "Ansible Subnet"
subnet_cidr: 10.10.0.0/26

igw_name: "Traffic IGW"


#route table name
route_name: "Public Ansible"

securitygroup_name: "Ansible Security Group"

ec2_tag: "WebServer"


#key storage location
ec2_key_directory: "/home/ansible/keystore-test/"
keypair_name: "ansible_key"

